# Generated by Django 5.0.4 on 2024-05-03 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='parent_team',
            new_name='parent',
        ),
    ]
