# Generated by Django 5.0.4 on 2024-04-27 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_date', models.DateField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
            ],
        ),
        migrations.CreateModel(
            name='AvailabilityPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.AddField(
            model_name='availability',
            name='friday',
            field=models.ManyToManyField(related_name='friday', to='employees.availabilityperiod'),
        ),
        migrations.AddField(
            model_name='availability',
            name='monday',
            field=models.ManyToManyField(related_name='monday', to='employees.availabilityperiod'),
        ),
        migrations.AddField(
            model_name='availability',
            name='saturday',
            field=models.ManyToManyField(related_name='saturday', to='employees.availabilityperiod'),
        ),
        migrations.AddField(
            model_name='availability',
            name='sunday',
            field=models.ManyToManyField(related_name='sunday', to='employees.availabilityperiod'),
        ),
        migrations.AddField(
            model_name='availability',
            name='thursday',
            field=models.ManyToManyField(related_name='thursday', to='employees.availabilityperiod'),
        ),
        migrations.AddField(
            model_name='availability',
            name='tuesday',
            field=models.ManyToManyField(related_name='tuesday', to='employees.availabilityperiod'),
        ),
        migrations.AddField(
            model_name='availability',
            name='wednesday',
            field=models.ManyToManyField(related_name='wednesday', to='employees.availabilityperiod'),
        ),
    ]
