# Generated by Django 5.0.4 on 2024-05-03 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_employee_date_of_birth_alter_employee_email_and_more'),
        ('teams', '0002_rename_parent_team_team_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='managed_teams',
            field=models.ManyToManyField(blank=True, null=True, related_name='managed_by', to='teams.team'),
        ),
    ]
