# Generated by Django 5.0.4 on 2024-04-27 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_availability_availabilityperiod_delete_test_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availability',
            options={'verbose_name_plural': 'Availabilities'},
        ),
        migrations.AddField(
            model_name='availability',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
