# Generated by Django 5.0.4 on 2024-05-03 12:56

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='color',
            field=colorfield.fields.ColorField(choices=[('#000000', 'black'), ('#696969', 'dimgray'), ('#808080', 'gray'), ('#A9A9A9', 'darkgray'), ('#C0C0C0', 'silver'), ('#D3D3D3', 'lightgray'), ('#DCDCDC', 'gainsboro'), ('#FF0000', 'red'), ('#A52A2A', 'brown'), ('#FF4500', 'orangered'), ('#FFA500', 'orange'), ('#FFFF00', 'yellow'), ('#9ACD32', 'yellowgreen'), ('#008000', 'green'), ('#20B2AA', 'lightseagreen'), ('#00FFFF', 'aqua'), ('#00BFFF', 'deepskyblue'), ('#4169E1', 'royalblue'), ('#7B68EE', 'mediumslateblue'), ('#DA70D6', 'orchid')], default='#FFFFFF', image_field=None, max_length=25, samples=None),
        ),
    ]
